#cloud-config

packages:
  - ca-certificates
  - curl
  - coreutils
  - tar
  - gzip
  - gnupg

runcmd:
  - curl -fsSL https://packagecloud.io/install/repositories/circleci/runner/script.rpm.sh?any=true | bash
  - sudo yum install circleci-runner -y
  - sudo sed -i "s/<< AUTH_TOKEN >>/$RUNNER_AUTH_TOKEN/g" /etc/circleci-runner/circleci-runner-config.yaml
  - sudo systemctl enable circleci-runner
  - sudo systemctl start circleci-runner